/**
 * Raw draft of the starter class of the $classDescriptor.getMetaInfoValueFor("pluginID") plugin.
 * TODO: Complete the implementation manually.
 * @author generated by MOGLi Code Creator
 */

#set( $pluginType = $classDescriptor.getMetaInfoValueFor("pluginType") )

#if ($classDescriptor.getMetaInfoValueFor("isMetaInfoValidatorVendor") == "true")

	#set( $interfaces = ", MetaInfoValidatorVendor" )

#else

	#set( $interfaces = "" )

#end

#if ($pluginType == "GENERATOR")

	public class ${classDescriptor.simpleName} implements Generator$interfaces {

#elseif ($pluginType == "MODEL_PROVIDER")

	public class ${classDescriptor.simpleName} implements ModelProvider$interfaces {

#elseif ($pluginType == "DATA_PROVIDER")

	public class ${classDescriptor.simpleName} implements DataProvider$interfaces {

#elseif ($pluginType == "ENGINE_PROVIDER")

	public class ${classDescriptor.simpleName} implements EngineProvider$interfaces {

#else

	unknown pluginType: $pluginType

#end
