package de.validator;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import de.Test;
import de.validator.helper.*;
import de.validator.types.*;


/**
* Validator class of the MOGLiCC JavaBean Group for JavaBean 'Test.java'
*
* @author generated by MOGLiCC
*/
public class TestValidator extends JavaBeanValidator {

	private static TestValidator instance;

	public static void doYourJob(final Test data) {
		if (instance == null) {
			instance = new TestValidator();
		} else {
			instance.validationErrors.clear();
		}
		instance.validate(data);
	}

	public TestValidator() {
		validationErrors = new ArrayList<String>();
		validators = new HashMap<String, List<FieldValidator>>();
		List<FieldValidator> validatorList;
	}

	private void validate(final Test toValidate) {

		if (validationErrors.size() > 0) {
			throw new FieldValidationException(buildErrorMessage( "Test" ));
		}
	}

}