#set( $targetDir = $model.getMetaInfoValueFor("targetDir") )
#set( $packagePath = $TemplateStringUtility.replaceAllIn(${classDescriptor.package}, ".", "/") )

@TargetFileName ${classDescriptor.simpleName}.java 
@TargetDir $targetDir/hello_word_advanced_example/file_maker/src/$packagePath
@NameOfValidModel HelloWorldAdvancedExample
@CreateNew true

package ${classDescriptor.package};
'
/**
	#set( $commentList = ${classDescriptor.getAllMetaInfoValuesFor("comment")} ) 
	#foreach($comment in $commentList)
		' * $comment		
	#end
' * @author autogenerated by MOGLiCC
' */
public class ${classDescriptor.simpleName} 
{
'	public static void main(String[] args) {

		#set( $greeting = "" ) 		
		#foreach($attributeDescriptor in $classDescriptor.attributeDescriptorList)
		
			#set( $type = ${attributeDescriptor.getMetaInfoValueFor("type")} ) 
			
			#if ( $type == "String" )
				#set( $greeting = $greeting + $attributeDescriptor.name + " ") 
			#elseif ( $type == "Char" )
				#set( $greeting = $greeting.trim() + $attributeDescriptor.getMetaInfoValueFor("value") ) 	
			#end

		#end
		
		#if ( $greeting.length() == 0)
			'		// TODO: MOGLiCC found no data here
		#else
			'		System.out.println("$greeting");
		#end
'	}
}
<<<<<<< HEAD

=======
>>>>>>> 656c84c58ad794ed34c58c30ecc9bf656c921412
