package de.builder;

import static org.junit.Assert.*;

import org.junit.*;

import java.util.*;

import de.*;
import de.builder.*;
import de.factory.*;
import de.utils.*;


/**
* Tests basic functionality of the 'TestBuilder.'
*
* @author generated by MOGLiCC
*/
public class TestBuilderUnitTest {

	@Test
	public void buildsEmptyTestInstance() {
		TestBuilder builder = new TestBuilder();
		Test instance = builder.build();
	}

	@Test
	public void buildsExampleTestInstance() {
		TestBuilder builder = new TestBuilder();


		Test instance = builder.build();

	}

}