package a.validator;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import a.CorrectClassName;
import a.validator.helper.*;
import a.validator.types.*;


/**
* Validator class of the MOGLiCC JavaBean Group for JavaBean 'CorrectClassName.java'
*
* @author generated by MOGLiCC
*/
public class CorrectClassNameValidator extends JavaBeanValidator {

	private static CorrectClassNameValidator instance;

	public static void doYourJob(final CorrectClassName data) {
		if (instance == null) {
			instance = new CorrectClassNameValidator();
		} else {
			instance.validationErrors.clear();
		}
		instance.validate(data);
	}

	public CorrectClassNameValidator() {
		validationErrors = new ArrayList<String>();
		validators = new HashMap<String, List<FieldValidator>>();
		List<FieldValidator> validatorList;
	}

	private void validate(final CorrectClassName toValidate) {

		if (validationErrors.size() > 0) {
			throw new FieldValidationException(buildErrorMessage( "CorrectClassName" ));
		}
	}

}