package a.builder;

import static org.junit.Assert.*;

import org.junit.*;

import java.util.*;

import a.*;
import a.builder.*;
import a.factory.*;
import a.utils.*;


/**
* Tests basic functionality of the 'CorrectClassNameBuilder.'
*
* @author generated by MOGLiCC
*/
public class CorrectClassNameBuilderUnitTest {

	@Test
	public void buildsEmptyCorrectClassNameInstance() {
		CorrectClassNameBuilder builder = new CorrectClassNameBuilder();
		CorrectClassName instance = builder.build();
	}

	@Test
	public void buildsExampleCorrectClassNameInstance() {
		CorrectClassNameBuilder builder = new CorrectClassNameBuilder();


		CorrectClassName instance = builder.build();

	}

}