<<<<<<< HEAD
package com.iksgmbh.moglicc.moglicc;

/**
 * Hello World example 3 for the MOGLi Code Creator.
 * This examples demonstrates the line inserter function.
 * @author autogenerated by MOGLiCC
 */
public class HelloWorldGreeting3
{
	public static void main(String[] args) {
		/** START replace MOGLiCC marker !!! Do not modify this line !!! */
		/** END replace MOGLiCC marker !!! Do not modify this line !!! */
	}
}
=======
package com.iksgmbh.moglicc.moglicc;

/**
 * Hello World example 3 for the MOGLi Code Creator.
 * This examples demonstrates the line inserter function.
 * @author autogenerated by MOGLiCC
 */
public class HelloWorldGreeting3
{
	public static void main(String[] args) {
		/** START replace MOGLiCC marker !!! Do not modify this line !!! */
		/** END replace MOGLiCC marker !!! Do not modify this line !!! */
	}
}
>>>>>>> 9fc3cbd437cf194e6ad0560123dd6958fe55cdfc
