package de;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import com.iksgmbh.moglicc.demo.validator.FieldValidationException;
import com.iksgmbh.moglicc.demo.validator.FieldValidator;
import com.iksgmbh.moglicc.demo.validator.JavaBeanValidator;
import com.iksgmbh.moglicc.demo.validator.types.MandatoryFieldValidator;
import com.iksgmbh.moglicc.demo.validator.types.MaxLengthValidator;
import com.iksgmbh.moglicc.demo.validator.types.MinLengthValidator;


/**
* Validator class of the MOGLiCC JavaBean Group for JavaBean 'Test.java'
*
* @author generated by MOGLiCC
*/
public class TestValidator extends JavaBeanValidator {

	private static TestValidator instance;

	public static void doYourJob(final Test data) {
		if (instance == null) {
			instance = new TestValidator();
		} else {
			instance.validationErrors.clear();
		}
		instance.validate(data);
	}

	public TestValidator() {
		validationErrors = new ArrayList<String>();
		validators = new HashMap<String, List<FieldValidator>>();
		List<FieldValidator> validatorList;
	}

	private void validate(final Test toValidate) {

		if (validationErrors.size() > 0) {
			throw new FieldValidationException(buildErrorMessage());
		}
	}

}