package de;


/**
* JavaBean class of the MOGLiCC JavaBean Group
*
* @author generated by MOGLiCC
*/
public class Test
{
	// instance fields

	// ===============  setter methods  ===============

	// ===============  getter methods  ===============

	// ===============  additional Javabean methods  ===============

	@Override
	public String toString()
	{
		return "Test ["
				+ "]";
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;

		final Test other = (Test) obj;

		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;


		return result;
	}

}