package <projectPath>;

/**
 * Hello World example 4 for the MOGLi Code Creator.
 * This examples demonstrates the tree builder function.
 * @author autogenerated by MOGLiCC
 */
public class <ClassName>
{
	public static void main(String[] args) {
		System.out.println("<greeting>");
	}
}
