package a;

import static org.junit.Assert.*;

import org.junit.*;

import a.*;
import a.builder.*;
import a.validator.*;
import a.factory.*;
import a.utils.*;


/**
* Tests basic JavaBean functionality for JavaBean 'CorrectClassName.java'
*
* @author generated by MOGLiCC
*/
public class CorrectClassNameUnitTest {

	private CorrectClassName correctClassName1;
	private CorrectClassName correctClassName2;

	@Before
	public void setup() {
		final CorrectClassNameBuilder builder = new CorrectClassNameBuilder();
		correctClassName1 = builder
		          .build();
		correctClassName2 = builder.build();
	}

	@Test
	public void returnsTrueWhenCallingEqualsMethodWithEqualCorrectClassNameInstance() {
		assertTrue("unequal instances", correctClassName1.equals(correctClassName1));
		assertTrue("unequal instances", correctClassName1.equals(correctClassName2));
	}

	@Test
	public void buildsEqualHashCodesForEqualCorrectClassNameInstances() {
		assertTrue("unequal instances", correctClassName1.hashCode() == correctClassName1.hashCode());
		assertTrue("unequal instances", correctClassName2.hashCode() == correctClassName2.hashCode());
	}




	// method 'createsNewCorrectClassNameInstancesUsing_CloneWith_MethodOfBuilder()' could not be created, because
	// only one attribute exists for class 'CorrectClassName'

}