@TargetFileName ${classDescriptor.simpleName}.java # Name of output file with extension but without path
@TargetDir $model.getMetaInfoValueFor("eclipseProjectDir")/$model.getMetaInfoValueFor("projectName")/src/main/java/<package>
@CreateNew true # creates target dir if not existing and overwrites target file if existing
@NameOfValidModel MOGLiCC_JavaBeanModel

package ${classDescriptor.package};
'
#parse("commonSubtemplates/importDomainModelClasses.tpl")
'
/**
 * JavaBean class of the MOGLiCC JavaBean Group
 *
 * @author generated by MOGLiCC
 */
#parse("C_ClassDefinitionLine.tpl")
{
	#parse("D_Serializable.tpl")

	#parse("E_Variables.tpl")

	#parse("F_SetterMethods.tpl")

	#parse("G_GetterMethods.tpl")

'	// ===============  additional Javabean methods  ===============
'
	#parse("H_toStringMethod.tpl")

'
	#parse("I_equalsMethod.tpl")

'
	#parse("J_hashCodeMethod.tpl")

'

#if ( $classDescriptor.doesHaveMetaInfo( "implements", "Cloneable") )

	#parse("K_cloneMethod.tpl")

#end
}