@TargetFileName ${classDescriptor.simpleName}Validator.java # Name of output file with extension but without path
@TargetDir $model.getMetaInfoValueFor("eclipseProjectDir")/$model.getMetaInfoValueFor("projectName")/src/main/java/<package>
@CreateNew true # creates target dir if not existing and overwrites target file if existing
@NameOfValidModel MOGLiCC_JavaBeanModel

package ${classDescriptor.package};
'
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
'
import com.iksgmbh.moglicc.demo.validator.FieldValidationException;
import com.iksgmbh.moglicc.demo.validator.FieldValidator;
import com.iksgmbh.moglicc.demo.validator.JavaBeanValidator;
import com.iksgmbh.moglicc.demo.validator.types.MandatoryFieldValidator;
import com.iksgmbh.moglicc.demo.validator.types.MaxLengthValidator;
import com.iksgmbh.moglicc.demo.validator.types.MinLengthValidator;
'
#parse("commonSubtemplates/B_ImportStatements.tpl")
'
/**
 * Validator class of the MOGLiCC JavaBean Group for JavaBean '${classDescriptor.simpleName}.java'
 *
 * @author generated by MOGLiCC
 */
public class ${classDescriptor.simpleName}Validator extends JavaBeanValidator {
'
'	private static ${classDescriptor.simpleName}Validator instance;
'
'	public static void doYourJob(final ${classDescriptor.simpleName} data) {
'		if (instance == null) {
'			instance = new ${classDescriptor.simpleName}Validator();
'		} else {
'			instance.validationErrors.clear();
'		}
'		instance.validate(data);
'	}
'
	#parse("C_Constructor.tpl")

'

	#parse("D_validateMethod.tpl")

'
}