package a.validator;

import static org.junit.Assert.*;

import org.junit.Before;
import org.junit.Test;

import a.*;
import a.builder.*;
import a.validator.*;
import a.factory.*;
import a.utils.*;


/**
* Tests basic validator functionality for 'CorrectClassNameValidator.java'
*
* @author generated by MOGLiCC
*/
public class CorrectClassNameValidatorUnitTest {

	private CorrectClassName testData;

	@Before
	public void setup() {
		final CorrectClassNameBuilder builder = new CorrectClassNameBuilder();
		testData = builder
		          .build();
	}

	@Test
	public void validatesWithoutErrorIfAllFieldsAreSetCorrectly() {
		try {
			CorrectClassNameValidator.doYourJob(testData);
		} catch (Exception e) {
			System.err.println(e.getMessage());
			fail("No exception expected !");
		}
	}




	@Test
	public void validatesWithMultipleValidationErrors() {

		try {
			CorrectClassNameValidator.doYourJob(testData);
			fail("Expected exception not thrown!");
		} catch (Exception e) {
			System.err.println(e.getMessage());
			assertTrue("unexpected error message", e.getMessage().startsWith("0 validation errors exist for 'CorrectClassName'"));
			return;
		}
// there is no validation definfed for CorrectClassName
	}

	@Test
	public void validatesWithMultipleErrorMessageForNotReachingMinLength() {
		final CorrectClassName instance = CorrectClassNameFactory.createInstanceWithAllSupportedFieldsNotReachingMinLength();

// the meta model contains for class 'CorrectClassName' no attribute with metainfo 'MinLength', therefore is no test in this method possible

	}

	@Test
	public void validatesWithMultipleErrorMessageForExceedingMaxLength() {
		final CorrectClassName instance = CorrectClassNameFactory.createInstanceWithAllSupportedFieldsExceedingMaxLength();

// the meta model contains for class 'CorrectClassName' no attribute with metainfo 'MaxLength', therefore is no test in this method possible

	}


}