package de.builder;

import de.Test;
import de.validator.TestValidator;
/**
* Builder class of the MOGLiCC JavaBean Group for JavaBean 'Test.java'
*
* @author generated by MOGLiCC
*/
public class TestBuilder {

	private Test toBuild;

	public TestBuilder(final Test data) {
		this.toBuild = cloneTest(data);
	}

	public TestBuilder() {
		this.toBuild = new Test();
	}

	public Test build() {
		return cloneTest(toBuild);
	}

	public Test buildAndValidate() {
		final Test toReturn = cloneTest(toBuild);
		try {
			TestValidator.doYourJob(toReturn);
		} catch (Exception e) {
			e.printStackTrace();
		}
		return toReturn;
	}



	public Test cloneTest(final Test object) {
		// Alternatively use clone method generated for BuildUpClassDescriptor [classname=de.Test, attributeNumber=0, metaInfoList=Single]
		final Test toReturn = new Test();
		return toReturn;
	}
}