package de;

import static org.junit.Assert.*;

import org.junit.Before;
import org.junit.Test;

/**
* Tests basic validator functionality for 'TestValidator.java'
*
* @author generated by MOGLiCC
*/
public class TestValidatorUnitTest {

	private Test testData;

	@Before
	public void setup() {
		final TestBuilder builder = new TestBuilder();
		testData = builder
		          .build();
	}

	@Test
	public void validatesWithoutErrorIfAllFieldsAreSetCorrectly() {
		TestValidator.doYourJob(testData);
	}



}